// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: src/config/grpc/server/protos/health.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage =
  "vn.techres.microservice.grpc.nodejs.nestjs_system_invoice.health";

/** No parameters required */
export interface HealthCheckRequest {}

export interface HealthCheckResponse {
  status: number;
  message: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_NESTJS_SYSTEM_INVOICE_HEALTH_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs.nestjs_system_invoice.health";

export interface HealthServiceClient {
  check(
    request: HealthCheckRequest,
    metadata?: Metadata
  ): Observable<HealthCheckResponse>;
}

export interface HealthServiceController {
  check(
    request: HealthCheckRequest,
    metadata?: Metadata
  ):
    | Promise<HealthCheckResponse>
    | Observable<HealthCheckResponse>
    | HealthCheckResponse;
}

export function HealthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["check"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod("HealthService", method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod("HealthService", method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const HEALTH_SERVICE_NAME = "HealthService";
