// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: src/config/grpc/server/protos/partner.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage =
  "vn.techres.microservice.grpc.nodejs.nestjs_system_invoice.login_partner.invoice";

export interface CheckAccountPartnerRequest {
  type: number;
  taxcode: string;
  username: string;
  password: string;
  usernameAccessService: string;
  passwordAccessService: string;
  endpoint: string;
}

export interface CheckAccountPartnerResponse {
  success: number;
  message: string;
  data: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_NESTJS_SYSTEM_INVOICE_LOGIN_PARTNER_INVOICE_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs.nestjs_system_invoice.login_partner.invoice";

export interface PartnerServiceClient {
  checkAccountPartner(
    request: CheckAccountPartnerRequest,
    metadata?: Metadata
  ): Observable<CheckAccountPartnerResponse>;
}

export interface PartnerServiceController {
  checkAccountPartner(
    request: CheckAccountPartnerRequest,
    metadata?: Metadata
  ):
    | Promise<CheckAccountPartnerResponse>
    | Observable<CheckAccountPartnerResponse>
    | CheckAccountPartnerResponse;
}

export function PartnerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAccountPartner"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod("PartnerService", method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod("PartnerService", method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const PARTNER_SERVICE_NAME = "PartnerService";
